### ISSUE TITLE
Bagian atas ayat kepotong

### ISSUE THREAD

**Issue by stephnradd** [dapoi/Muslim-Q#7]
Di versi 1.8 bagian Al-Qur'an, bagian atas ayat terpotong sehingga tanda waqafnya tidak terlihat. Hal ini cukup mengganggu saat digunakan untuk tadarus.

**Comment by dapoi** [comment]
Halo kak,

Sebelumnya mohon maaf atas permasalahannya, bisa diinfokan kak terkait
tampilan yang terpotong? Agar bisa disesuaikan sesuai dengan device 🙏

Terima kasih banyak atas laporannya ya ❤️

**Comment by stephnradd** [comment]
![Screenshot_20230725-063808](https://github.com/dapoi/Muslim-Q/assets/70277944/8075dbb1-60dc-4c8d-a1fa-ca1bba7c9b48)
Izin ya pak, ini Al-Baqarah ayat 2 kan ada tanda waqaf setalah kata fīh(i) tapi tidak keliatan

oya ini layar hp saya 415 dpi

**Comment by dapoi** [comment]
Baik terima kasih banyak ya kak atas screenshot nya, akan kami perbaiki di
update-an berikutnya yaa.

Terima kasih & sehat selalu ❤️❤️
